# Generated by Django 2.0.2 on 2018-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisasi_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakulti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukm_per', models.CharField(max_length=7)),
                ('nama', models.CharField(max_length=100)),
                ('status_semasa', models.CharField(max_length=100)),
                ('status_cuti', models.CharField(blank=True, max_length=100)),
                ('jabatan', models.CharField(max_length=255)),
                ('fakulti', models.CharField(max_length=255)),
                ('jawatan', models.CharField(max_length=255)),
                ('lantikan', models.CharField(blank=True, max_length=255, null=True)),
                ('tarikh_lantikan', models.CharField(blank=True, max_length=255, null=True)),
                ('tarikh_tamat_jawatan', models.CharField(blank=True, max_length=255, null=True)),
                ('tarikh_mula_cuti', models.CharField(blank=True, max_length=255, null=True)),
                ('tarikh_tamat_cuti', models.CharField(blank=True, max_length=255, null=True)),
                ('jam_latihan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
