# Generated by Django 2.0.2 on 2018-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisasi_data', '0002_fakulti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Fakulti',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
